const mongoose = require("mongoose");
const dotenv = require("dotenv");
const Product = require("./models/Product");

dotenv.config();

const products = [
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Vintage Camera',
    price: 49,
    description: 'A classic film camera with a retro design.',
    primaryImage: 'https://images.pexels.com/photos/1021693/pexels-photo-1021693.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1183428/pexels-photo-1183428.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Vintage Camera - Front View',
    secondaryAlt: 'Vintage Camera - Side View',
    categorySlug: 'electronics',
    type: 'physical',
    createdAt: new Date('2025-04-01T10:00:00Z'),
    updatedAt: new Date('2025-04-01T10:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Leather Notebook',
    price: 29,
    description: 'Handcrafted leather notebook for journaling.',
    primaryImage: 'https://images.pexels.com/photos/159750/open-book-book-pages-literature-159750.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/415071/pexels-photo-415071.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Leather Notebook - Cover',
    secondaryAlt: 'Leather Notebook - Open',
    categorySlug: 'stationery',
    type: 'physical',
    createdAt: new Date('2025-04-02T12:00:00Z'),
    updatedAt: new Date('2025-04-02T12:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Ceramic Mug',
    price: 15,
    description: 'Handmade ceramic mug with a minimalist design.',
    primaryImage: 'https://images.pexels.com/photos/903661/pexels-photo-903661.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1098378/pexels-photo-1098378.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Ceramic Mug - Front',
    secondaryAlt: 'Ceramic Mug - Side',
    categorySlug: 'kitchen',
    type: 'physical',
    createdAt: new Date('2025-04-03T14:00:00Z'),
    updatedAt: new Date('2025-04-03T14:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Wooden Watch',
    price: 89,
    description: 'Eco-friendly wooden watch with quartz movement.',
    primaryImage: 'https://images.pexels.com/photos/2783873/pexels-photo-2783873.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/2113994/pexels-photo-2113994.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Wooden Watch - Face',
    secondaryAlt: 'Wooden Watch - Band',
    categorySlug: 'accessories',
    type: 'physical',
    createdAt: new Date('2025-04-04T16:00:00Z'),
    updatedAt: new Date('2025-04-04T16:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Minimalist Lamp',
    price: 59,
    description: 'Modern minimalist desk lamp with LED light.',
    primaryImage: 'https://images.pexels.com/photos/112811/pexels-photo-112811.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/271816/pexels-photo-271816.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Minimalist Lamp - Lit',
    secondaryAlt: 'Minimalist Lamp - Off',
    categorySlug: 'home-decor',
    type: 'physical',
    createdAt: new Date('2025-04-05T18:00:00Z'),
    updatedAt: new Date('2025-04-05T18:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Wool Blanket',
    price: 75,
    description: 'Soft and warm wool blanket for cozy nights.',
    primaryImage: 'https://images.pexels.com/photos/322207/pexels-photo-322207.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1704121/pexels-photo-1704121.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Wool Blanket - Folded',
    secondaryAlt: 'Wool Blanket - Spread Out',
    categorySlug: 'home-decor',
    type: 'physical',
    createdAt: new Date('2025-04-06T20:00:00Z'),
    updatedAt: new Date('2025-04-06T20:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Artisan Candle',
    price: 22,
    description: 'Scented artisan candle in ceramic jar.',
    primaryImage: 'https://images.pexels.com/photos/1866149/pexels-photo-1866149.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1944496/pexels-photo-1944496.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Candle - Top View',
    secondaryAlt: 'Candle - Side View',
    categorySlug: 'home-decor',
    type: 'physical',
    createdAt: new Date('2025-04-07T22:00:00Z'),
    updatedAt: new Date('2025-04-07T22:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Canvas Backpack',
    price: 64,
    description: 'Durable canvas backpack with leather straps.',
    primaryImage: 'https://images.pexels.com/photos/1204465/pexels-photo-1204465.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1027130/pexels-photo-1027130.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Backpack - Front',
    secondaryAlt: 'Backpack - Back',
    categorySlug: 'accessories',
    type: 'physical',
    createdAt: new Date('2025-04-08T10:00:00Z'),
    updatedAt: new Date('2025-04-08T10:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Enamel Pin Set',
    price: 18,
    description: 'Set of colorful enamel pins for bags or jackets.',
    primaryImage: 'https://images.pexels.com/photos/1099680/pexels-photo-1099680.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/3771865/pexels-photo-3771865.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Pin Set - Close-up',
    secondaryAlt: 'Pin Set - Spread',
    categorySlug: 'accessories',
    type: 'physical',
    createdAt: new Date('2025-04-09T12:00:00Z'),
    updatedAt: new Date('2025-04-09T12:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Wicker Basket',
    price: 35,
    description: 'Handwoven wicker basket for storage or decor.',
    primaryImage: 'https://images.pexels.com/photos/2129912/pexels-photo-2129912.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/2566247/pexels-photo-2566247.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Basket - Empty',
    secondaryAlt: 'Basket - With Blankets',
    categorySlug: 'home-decor',
    type: 'physical',
    createdAt: new Date('2025-04-10T14:00:00Z'),
    updatedAt: new Date('2025-04-10T14:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Succulent Trio',
    price: 19,
    description: 'Set of 3 mini succulents in ceramic pots.',
    primaryImage: 'https://images.pexels.com/photos/569966/pexels-photo-569966.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1048037/pexels-photo-1048037.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Succulent Set - Top View',
    secondaryAlt: 'Succulent Set - Side View',
    categorySlug: 'home-decor',
    type: 'physical',
    createdAt: new Date('2025-04-11T16:00:00Z'),
    updatedAt: new Date('2025-04-11T16:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Desk Organizer',
    price: 27,
    description: 'Wooden desk organizer for pens and accessories.',
    primaryImage: 'https://images.pexels.com/photos/280680/pexels-photo-280680.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1599321/pexels-photo-1599321.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Desk Organizer - Filled',
    secondaryAlt: 'Desk Organizer - Empty',
    categorySlug: 'stationery',
    type: 'physical',
    createdAt: new Date('2025-04-12T18:00:00Z'),
    updatedAt: new Date('2025-04-12T18:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Fabric Tote Bag',
    price: 16,
    description: 'Eco-friendly tote bag with hand-printed design.',
    primaryImage: 'https://images.pexels.com/photos/4450401/pexels-photo-4450401.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/5025517/pexels-photo-5025517.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Tote Bag - Hanging',
    secondaryAlt: 'Tote Bag - Worn',
    categorySlug: 'accessories',
    type: 'physical',
    createdAt: new Date('2025-04-13T20:00:00Z'),
    updatedAt: new Date('2025-04-13T20:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Metal Bookmark',
    price: 12,
    description: 'Elegant metal bookmark with engraved details.',
    primaryImage: 'https://images.pexels.com/photos/257461/pexels-photo-257461.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/46274/bookmark-love-paper-romance-46274.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Bookmark - In Book',
    secondaryAlt: 'Bookmark - Close View',
    categorySlug: 'stationery',
    type: 'physical',
    createdAt: new Date('2025-04-14T22:00:00Z'),
    updatedAt: new Date('2025-04-14T22:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Glass Water Bottle',
    price: 32,
    description: 'Eco-friendly glass water bottle with bamboo lid.',
    primaryImage: 'https://images.pexels.com/photos/1451445/pexels-photo-1451445.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1323550/pexels-photo-1323550.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Water Bottle - Closed',
    secondaryAlt: 'Water Bottle - Open',
    categorySlug: 'kitchen',
    type: 'physical',
    createdAt: new Date('2025-04-15T10:00:00Z'),
    updatedAt: new Date('2025-04-15T10:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Travel Journal',
    price: 26,
    description: 'Compact journal for capturing travel memories.',
    primaryImage: 'https://images.pexels.com/photos/1843717/pexels-photo-1843717.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/1978259/pexels-photo-1978259.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Travel Journal - Closed',
    secondaryAlt: 'Travel Journal - Open',
    categorySlug: 'stationery',
    type: 'physical',
    createdAt: new Date('2025-04-16T12:00:00Z'),
    updatedAt: new Date('2025-04-16T12:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Eucalyptus Spray',
    price: 20,
    description: 'Refreshing natural room spray with eucalyptus oil.',
    primaryImage: 'https://images.pexels.com/photos/41103/aromatherapy-spa-skin-41103.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/2349692/pexels-photo-2349692.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Spray Bottle - Standing',
    secondaryAlt: 'Spray Bottle - Side',
    categorySlug: 'personal-care',
    type: 'physical',
    createdAt: new Date('2025-04-17T14:00:00Z'),
    updatedAt: new Date('2025-04-17T14:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Coaster Set',
    price: 14,
    description: 'Set of 4 cork coasters with printed patterns.',
    primaryImage: 'https://images.pexels.com/photos/2781835/pexels-photo-2781835.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/709867/pexels-photo-709867.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Coasters - Stacked',
    secondaryAlt: 'Coasters - Spread',
    categorySlug: 'kitchen',
    type: 'physical',
    createdAt: new Date('2025-04-18T16:00:00Z'),
    updatedAt: new Date('2025-04-18T16:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Mini Plant Stand',
    price: 34,
    description: 'Wooden plant stand for small indoor pots.',
    primaryImage: 'https://images.pexels.com/photos/450326/pexels-photo-450326.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/209339/pexels-photo-209339.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Plant Stand - Side View',
    secondaryAlt: 'Plant Stand - With Plant',
    categorySlug: 'home-decor',
    type: 'physical',
    createdAt: new Date('2025-04-19T18:00:00Z'),
    updatedAt: new Date('2025-04-19T18:00:00Z'),
  },
  {
    _id: new mongoose.Types.ObjectId(),
    name: 'Bamboo Toothbrush Set',
    price: 17,
    description: 'Eco-friendly bamboo toothbrushes in a pack of 4.',
    primaryImage: 'https://images.pexels.com/photos/3735213/pexels-photo-3735213.jpeg?auto=compress&cs=tinysrgb&w=800',
    secondaryImage: 'https://images.pexels.com/photos/3735204/pexels-photo-3735204.jpeg?auto=compress&cs=tinysrgb&w=800',
    alt: 'Toothbrushes - Packaged',
    secondaryAlt: 'Toothbrushes - Spread',
    categorySlug: 'personal-care',
    type: 'physical',
    createdAt: new Date('2025-04-20T20:00:00Z'),
    updatedAt: new Date('2025-04-20T20:00:00Z'),
  },
];

mongoose
  .connect(process.env.MONGO_URI)
  .then(async () => {
    console.log("MongoDB connected!");

    await Product.deleteMany({});
    console.log("Old products removed.");

    await Product.insertMany(products);
    console.log("20 new products inserted!");

    mongoose.disconnect();
  })
  .catch((err) => {
    console.error("Error seeding products:", err);
  });
